try to use xdotool when wmctrl is not there

diff --git a/bin/current-desktop b/bin/current-desktop
--- a/bin/current-desktop
+++ b/bin/current-desktop
@@ -1,9 +1,12 @@
 #!/bin/sh
 
-if ! which wmctrl >/dev/null 2>&1; then
-  me=`basename $0`
-  echo "$me: wmctrl not found; aborting." >&2
-  exit 1
+if which wmctrl >/dev/null 2>&1; then
+    wmctrl -d -v 2>&1 | sed -ne '/^Current desktop ID.*: /{s///;p}'
+elif which xdotool >/dev/null 2>&1; then
+    xdotool get_desktop
+else
+    me=`basename $0`
+    echo "$me: didn't find wmctrl or xdotool; aborting." >&2
+    exit 1
 fi
 
-wmctrl -d -v 2>&1 | sed -ne '/^Current desktop ID.*: /{s///;p}'
diff --git a/bin/current-winid b/bin/current-winid
--- a/bin/current-winid
+++ b/bin/current-winid
@@ -3,17 +3,19 @@
 # Only ttys have $WINDOWID set correctly?
 # Firefox doesn't, anyway.
 
-if ! which wmctrl >/dev/null 2>&1; then
-  me=`basename $0`
-  echo "$me: wmctrl not found; aborting." >&2
-  exit 1
+if which wmctrl >/dev/null 2>&1; then
+    # Note that the exit in END is what determines the final exit status,
+    # even though the previous exit initiates the exit.
+    wmctrl -a :ACTIVE: -v 2>&1 \
+      | awk 'BEGIN { exit_status = 1 }
+             /^Using window:/ { print $3; exit_status = 0; exit } 
+             END { exit exit_status }' \
+    || exit 1
+elif which xdotool >/dev/null 2>&1; then
+    xdotool getactivewindow
+else
+    me=`basename $0`
+    echo "$me: didn't find wmctrl or xdotool; aborting." >&2
+    exit 1
 fi
-
-# Note that the exit in END is what determines the final exit status,
-# even though the previous exit initiates the exit.
-wmctrl -a :ACTIVE: -v 2>&1 \
-  | awk 'BEGIN { exit_status = 1 }
-         /^Using window:/ { print $3; exit_status = 0; exit } 
-         END { exit exit_status }' \
-|| exit 1
 
