try to catch corner case where Xft.dpi didn't get set
No idea why this can happen but just saw it on celtic.

diff --git a/bin/ggkg b/bin/ggkg
--- a/bin/ggkg
+++ b/bin/ggkg
@@ -44,6 +44,10 @@ case "$xrdb_dpi" in
     284)
         git_font_size=9
         ;;
+    '')
+        echo >&2 "ERROR: xrdb couldn't retrieve Xft.dpi"
+        exit 1
+        ;;
     *)
         echo >&2 "Don't know what git gui font size to set for dpi $xrdb_dpi"
         ;;
