*** empty log message ***

diff --git a/bin/run-with-local-X-display b/bin/run-with-local-X-display
--- a/bin/run-with-local-X-display
+++ b/bin/run-with-local-X-display
@@ -4,8 +4,9 @@ host=${HOST:-${HOSTNAME:-`hostname`}}
 host=${host%%.*}
 display_file=$HOME/.Xdisplay.$host
 if [ -e $display_file ]; then
-  export DISPLAY=`cat ~/.Xdisplay.$host`
+  . "$display_file"
   "$@"
 else
-  echo "$display_file does not exist; aborting."
+  echo "$display_file does not exist; aborting." >&2
+  exit 1
 fi
