use IP for get-connection-type

diff --git a/bin/synergyc-wrapper b/bin/synergyc-wrapper
--- a/bin/synergyc-wrapper
+++ b/bin/synergyc-wrapper
@@ -126,12 +126,23 @@ ensure_correct_invocation_running () {
 
 _log_it "pid $$ started up"
 
+read_conf
+if ! IP="`host $servername |
+              awk '/has address/ {print $4; found=1}
+                   END           {exit found==1 ? 0 : 1}'`"
+then
+    echo "Couldn't determine IP of $servername; can't check connection type"
+    IP=
+else
+    echo "$servername has IP $IP"
+fi
+
 while true; do
     read_conf
 
     if ! AC-online; then
         reason_not_to_run="AC power offline"
-    elif [ `get-connection-type "$servername"` != 'lan' ]; then
+    elif [ -n "$IP" ] && [ `get-connection-type "$IP"` != 'lan' ]; then
         reason_not_to_run="not on direct wired connection to $servername"
     elif ! grep -q $domainname /etc/resolv.conf; then
         # dnsdomainname doesn't get changed by DHCP for some reason
