make xterm-window iterate through all options, including urxvt-256color first

diff --git a/bin/xterm-window b/bin/xterm-window
--- a/bin/xterm-window
+++ b/bin/xterm-window
@@ -24,6 +24,17 @@ if [ "$1" == '--top-left' ]; then
     shift
 fi
 
-#xterm -fn $font -g $geometry "$@"
-#gnome-terminal --geometry=$geometry "$@"
-urxvt -fn $font -g $geometry "$@"
+if which urxvt-256color >/dev/null 2>&1; then
+    urxvt-256color -fn $font -g $geometry "$@"
+elif which urxvt >/dev/null 2>&1; then
+    urxvt -fn $font -g $geometry "$@"
+elif which rxvt-unicode >/dev/null 2>&1; then
+    rxvt-unicode -fn $font -g $geometry "$@"
+elif which gnome-terminal >/dev/null 2>&1; then
+    gnome-terminal --geometry=$geometry "$@"
+elif which xterm >/dev/null 2>&1; then
+    xterm -fn $font -g $geometry "$@"
+else
+    echo >&2 "ERROR: couldn't find any terminal program; aborting."
+    exit 1
+fi
